// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIuMtrTkcWwep8tiNoLDOaIwi8bizKtw',
    appId: '1:238789587393:web:18f98cdba7b27a645abf40',
    messagingSenderId: '238789587393',
    projectId: 'nakliyatsistemi',
    authDomain: 'nakliyatsistemi.firebaseapp.com',
    storageBucket: 'nakliyatsistemi.firebasestorage.app',
    measurementId: 'G-DQRN3D4N3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLQNIEB2gZtf4jE114JMZ4XtL0IqtYfk',
    appId: '1:238789587393:android:c35cd429307d7bd15abf40',
    messagingSenderId: '238789587393',
    projectId: 'nakliyatsistemi',
    storageBucket: 'nakliyatsistemi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ow4VN50c7Ik-mMIoyny9afGAwNUoGPI',
    appId: '1:238789587393:ios:1780d52a8e20d0585abf40',
    messagingSenderId: '238789587393',
    projectId: 'nakliyatsistemi',
    storageBucket: 'nakliyatsistemi.firebasestorage.app',
    iosBundleId: 'com.example.243301011SengulSilaSahinFlutterProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ow4VN50c7Ik-mMIoyny9afGAwNUoGPI',
    appId: '1:238789587393:ios:1780d52a8e20d0585abf40',
    messagingSenderId: '238789587393',
    projectId: 'nakliyatsistemi',
    storageBucket: 'nakliyatsistemi.firebasestorage.app',
    iosBundleId: 'com.example.243301011SengulSilaSahinFlutterProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfIuMtrTkcWwep8tiNoLDOaIwi8bizKtw',
    appId: '1:238789587393:web:9d74bdb762c4757c5abf40',
    messagingSenderId: '238789587393',
    projectId: 'nakliyatsistemi',
    authDomain: 'nakliyatsistemi.firebaseapp.com',
    storageBucket: 'nakliyatsistemi.firebasestorage.app',
    measurementId: 'G-KCXWYFDK7S',
  );
}
